<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.iwhalecloud.bote</groupId>
    <artifactId>bote</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>bote-sms</artifactId>
  <description>短信模块：存放对接的各个平台短信功能</description>
  <packaging>pom</packaging>

  <modules>
    <module>bote-sms-bill</module>
  </modules>

</project>
