package com.iwhalecloud.bote.sms.bill.data;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-14T16:00:02.385+08:00
 * Generated source version: 4.0.3
 */
@WebService(targetNamespace = "http://intf.smpin.tydic.com", name = "BillDataSvrPortType")
@XmlSeeAlso(ObjectFactory.class)
public interface BillDataSvrPortType {

    @WebMethod(operationName = "BillInfo")
    @RequestWrapper(localName = "BillInfo", targetNamespace = "http://intf.smpin.tydic.com", className = "com.iwhalecloud.bote.sms.bill.data.BillInfo")
    @ResponseWrapper(localName = "BillInfoResponse", targetNamespace = "http://intf.smpin.tydic.com", className = "com.iwhalecloud.bote.sms.bill.data.BillInfoResponse")
    @WebResult(name = "BillResVo", targetNamespace = "")
    BillResVo billInfo(
        @WebParam(name = "UserVo", targetNamespace = "http://intf.smpin.tydic.com")
        UserVo userVo,
        @WebParam(name = "ArrayOfBillReqVo", targetNamespace = "http://intf.smpin.tydic.com")
        ArrayOfBillReqVo arrayOfBillReqVo
    );
}
