package com.iwhalecloud.bote.sms.bill.data;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-14T16:00:02.464+08:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "BillDataSvr",
                  wsdlLocation = "wsdl/BillDataServlet.wsdl",
                  targetNamespace = "http://intf.smpin.tydic.com")
public class BillDataSvr extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://intf.smpin.tydic.com", "BillDataSvr");
    public static final QName BillDataSvrHttpPort = new QName("http://intf.smpin.tydic.com", "BillDataSvrHttpPort");
    static {
        URL url = BillDataSvr.class.getResource("wsdl/BillDataServlet.wsdl");
        if (url == null) {
            url = BillDataSvr.class.getClassLoader().getResource("wsdl/BillDataServlet.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(BillDataSvr.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsdl/BillDataServlet.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillDataSvr(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillDataSvr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillDataSvr() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BillDataSvr(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BillDataSvr(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BillDataSvr(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BillDataSvrPortType
     */
    @WebEndpoint(name = "BillDataSvrHttpPort")
    public BillDataSvrPortType getBillDataSvrHttpPort() {
        return super.getPort(BillDataSvrHttpPort, BillDataSvrPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillDataSvrPortType
     */
    @WebEndpoint(name = "BillDataSvrHttpPort")
    public BillDataSvrPortType getBillDataSvrHttpPort(WebServiceFeature... features) {
        return super.getPort(BillDataSvrHttpPort, BillDataSvrPortType.class, features);
    }

}
